### ISSUE TITLE
آیا این پروژه واقعا یک BPMS کامل خواهد بود؟

### ISSUE THREAD

**Issue by Partak** [aminsharifi/Cheetah#2]
سلام، عرض ادب و احترام
بنده برنامه شما رو مشاهده کردم
خدا قوت میگم، امیدوارم در ادامه راه موفق باشید
با توجه به اینکه این برنامه Open Source هست و هدف گذاری BPMS رو برای خودش تعیین کرده، در ظاهر از یک فرآیند و تعدادی جدول تشکیل شده که حالت تعریف داینامیک در طراحی فرم، فیلد ها، خصوصیات دسترسی، دسترسی خروجی و ورودی Api، ورودی گردش کار و ... هنوز برای اون لحاظ نشده
سوال بنده این هست که آیا منظور شما از BPMS یک BPMS خصوصی محدود هست که فقط برای هدف کاری شما داره طراحی میشه و یا اینکه واقعا یک BPMS کامل رو شامل میشه
و مورد دیگه اینکه چه سازمان یا شرکتی از این طرح حمایت می کنه، از این بابت که آیا می توان به ادامه دار بودن این پروژه و ساخت یک BPMS کامل با تمام امکانات فرم ساز، Form Rendering، Workflow و گزارش ساز در آینده امیدوار بود یا خیر
از تلاش شما سپاسگزارم

**Comment by aminsharifi** [comment]
I am glad that this project was interesting for you.
If you find this open-source project useful, join its contributors.
As you mentioned there are many things that can contribute to the project.
