### ISSUE TITLE
Input json format

### ISSUE THREAD

**Issue by tabaee** [aminsharifi/Cheetah#4]
provide one sample for Input json format

**Comment by aminsharifi** [comment]
{
  "f_Request":
  {
    "rqt_ERPID":103,
    "rqt_Process":
    {
      "pName": "CustomerDefinition"
    },
    "rqt_Creator":
    {
        "pName": "m.tabatabaee"
    },
    "rqt_Requestor":
    {
        "pName": "a.sharifi"
    },
    "rqt_Conditions":
    [
      {
        "cd_Tag": 
        {
          "pName": "Price"
        },
        "cd_Value":"100"
      },
          {
        "cd_Tag": 
        {
          "pName": "FMCG"
        },
        "cd_Value":"1"
      }
    ]
  }
}

**Comment by tabaee** [comment]
{
"f_Request":
{
"rqt_ERPID":0,
"rqt_Process":
{
"pName": "ProductsOrdering"
},
"rqt_Creator":
{
"pName": "sm.tabatabaei"
},
"rqt_Requestor":
{
"pName": "b.zamanloo"
},
"rqt_Conditions":
[
{
"cd_Tag":
{
"pName": "Med"
},
"cd_Value":"1"
}
]
}
}

**Comment by aminsharifi** [comment]
mutation($f_Request:F_RequestInput!)
{
  createRequest (request:$f_Request)
  {
    id
    rqt_ProcessState        
    {
      pDisplayName
    }
    rqt_SelectedScenario
    {
      pDisplayName
    }
    rqt_Assignments
    {
      prm_Endorsement
      {
        pIndex
        ed_Role
        {
          pDisplayName
        }
        ed_Conditions
        {
          cd_Tag {
            pDisplayName
          }
          cd_Operand {
            pDisplayName
          }
          cd_Value
        }
      }
    }    
  }
}
